name: 'Hello World'
description: 'Greet the world and record the time'
author: 'Test Corporation'
icon: 'hello.svg' # vector art to display in the GitHub Marketplace
color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  plugin: 'checkout'
